### PR TITLE
fixed deprecated make_blobs() import

### PR DESCRIPTION
**Pull request by christian512**
Imported `make_blobs()` directly from `sklearn.datasets`

### CODE REVIEW

**Comment by amueller** [comment]
Thanks for the PR. What are you trying to accomplish with this fix? I left this in datasets so that people's code wouldn't break. The two functions don't have identical signatures.

**Comment by christian512** [comment]
Sorry, I did not see the differences in the implementation. However I was confused with the deprecated message in the provided notebooks (e.g. in `02-supervised-learning.ipynb`).

**Comment by amueller** [comment]
Thanks. The notebook should not import from there. Can you show me where the deprecation message is raised?

**Comment by amueller** [comment]
thanks, I'll look into fixing that!

**Comment by amueller** [comment]
should be fixed in master. Can you please check?

**Comment by christian512** [comment]
Seems like its working, thanks :)

**Pull request closed without merging**
