### PR TITLE
Proper label for Y-axis

### PR DESCRIPTION
**Pull request by humitos**
Hi @amueller!

This is my first-time contribution to a `.ipynb` file and _I have no idea_ how to do it properly since the cells are already executed. If I re-executed all of them in my Jupyter the diff gets giant.

Please, let me know which is the correct way of doing this or feel free to patch it by yourself. This PR is more a way to communicate where the typo is in an easy way.

Thanks for the book ;)

### CODE REVIEW

**Comment by humitos** [comment]
I took a look at other PRs and I found another that is similar to this one: https://github.com/amueller/introduction_to_ml_with_python/pull/14

So, I suppose that mine should be fine. Although, I suppose that the plot should be re-rendered and the base64 image that it's inside the `.ipynb` updated.

**Comment by humitos** [comment]
Just in case, I'm reading 3rd release printed version and this is on page 169.

**Comment by amueller** [comment]
I really thought I fixed this, let me double check.

**Comment by amueller** [comment]
Fixed in 52da2a9bbaa68d618e7742a25a1f95cd268c31e8. I had fixed it in the newest print of the book, but apparently it slipped through the cracks when I updated the notebooks in this repo.
Thanks for reporting!

**Comment by amueller** [comment]
I don't know why the diff here doesn't update, hm...

**Pull request closed without merging**
