### PR TITLE
Adjusting mglearn/datasets.py to use sklearn.datasets.make_blobs

### PR DESCRIPTION
**Pull request by meierale**
Since the use of sklearn.datasets.make_blobs is encouraged, mglearn/datasets.py was adjusted accordingly.

### CODE REVIEW

**Comment by amueller** [comment]
See #100 this is not the intention of the deprecation. I'll fix it.

**Comment by amueller** [comment]
Did you get a warning when using ``make_forge`` or when?

**Comment by meierale** [comment]
gosh ... sorry!

**Comment by amueller** [comment]
All good. Thanks for trying to help out :) the warning seems to show up in an unexpected place so I'm trying to figure out if it's anywhere in addition to ``make_forge``.

**Comment by amueller** [comment]
can you check if it's fixed now in master?

**Comment by meierale** [comment]
looking good so far!

in the original clone I did:
`git fetch --all`
and 
`git reset --hard origin/master`
to overwrite any local changes.. Opening 02-supervised-learning.ipynb works without error now. I also noticed you modified datasets.py. Didn't check any further ;-)

**Comment by amueller** [comment]
thanks :)

**Pull request closed without merging**
