### PR TITLE
import imread from scipy.ndimage instead of scipy.misc

### PR DESCRIPTION
**Pull request by dr0ptp4kt**
This gets a pip install'd Jupyter working well for figure 1-3's corresponding call grr = pd.scatter_matrix(...cmap = mglearn.cm3). It complains that it can't find imread otherwise for some reason.

### CODE REVIEW

**Comment by amueller** [comment]
That's weird. Which version of scipy do you have?

**Comment by amueller** [comment]
Also what exactly is the error message? This is somewhat confusing to me.

**Comment by dr0ptp4kt** [comment]
Just wanted to note I saw your questions. I'm on a different machine right now, so I'll need to get back to you about the specific version and error. But basically, the setup is this:

Mac OS X Yosemite
Python 3.5.2 installed via .pkg from python.org
Created a pyvenv
source bin/activate the pyvenv
In the pyvenv:
Ran the pip install <package list> as listed in the book.
Did a pip install jupyter to get jupyter

At first I was troubleshooting thinking I needed to do something like install Pillow / PIL, so I did a pip install pillow. But then I realized that even with those I would get same errors. So I did a pip uninstall pillow. I haven't gone through to track down the dependencies, but I wonder if you get the same thing if going the "vanilla install" route like this? (As opposed to use of Anaconda; I know, I know that's another option, although I like to get it running with the stock components when possible.)

**Comment by amueller** [comment]
You probably need a pip install pillow that I forgot in the book. But that should resolve the issue.
Unless it's compiling pillow from scratch (which I hope it wouldn't) and you don't have the libpng or libjpeg or what is used here.

It would be great if you could provide the full traceback when you're back on your other machine. Thanks!

**Comment by dr0ptp4kt** [comment]
I did do a pip install pillow, but that didn't fix the issue - changing the import did, though. That said, will get back to you on the traceback!

**Comment by dr0ptp4kt** [comment]
Hmm. So _this_ time after doing a pip install pillow it worked. Perhaps we can close out this case. What do you think about incorporating pillow as a dependency of mglearn so people get it automatically? I guess people will probably resolve it with a search engine query, but it might speed things up. I guess there's always the reprint, too :)

For the sake of completeness, here's what I was seeing for the versioning:
`
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> 
>>> print(" Python version: {}".format( sys.version))
 Python version: 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
>>> 
>>> import pandas as pd
>>> print(" pandas version: {}".format( pd.__version__))
 pandas version: 0.19.0
>>> 
>>> import matplotlib
>>> print(" matplotlib version: {}".
... format( matplotlib.__version__))
 matplotlib version: 1.5.3
>>> 
>>> import numpy as np
>>> print(" NumPy version: {}".format( np.__version__))
 NumPy version: 1.11.2
>>> 
>>> import scipy as sp
>>> print(" SciPy version: {}".format( sp.__version__))
 SciPy version: 0.18.1
>>> 
>>> import IPython
>>> print(" IPython version: {}".format( IPython.__version__))
 IPython version: 5.1.0
>>> 
>>> import sklearn
>>> print(" scikit-learn version: {}".format( sklearn.__version__))
 scikit-learn version: 0.18
>>> 
>>> import jupyter
>>> print(" jupyter version: {}".format( jupyter.__version__))
 jupyter version: 1.0.0
>>> 
`

And here's the code copied from the juypter cell, and the subsequent backtrace:

`

import scipy
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import mglearn

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris_dataset = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'],
                                                   iris_dataset['target'], random_state=0)

iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
grr = pd.scatter_matrix(iris_dataframe, c=y_train,
                       figsize=(15,15),
                       marker='o',
                       hist_kwds={'bins':20},s=60,alpha=.8,cmap=mglearn.cm3)


------------------------------------------------------------
ImportError                Traceback (most recent call last)
<ipython-input-1-059eb816fcfd> in <module>()
      4 get_ipython().magic('matplotlib inline')
      5 import pandas as pd
----> 6 import mglearn
      7 
      8 from sklearn.model_selection import train_test_split

/Users/me/programs/py3/lib/python3.5/site-packages/mglearn/__init__.py in <module>()
----> 1 from . import plots
      2 from . import tools
      3 from .plots import cm3, cm2
      4 from .tools import discrete_scatter
      5 from .plot_helpers import ReBl

/Users/me/programs/py3/lib/python3.5/site-packages/mglearn/plots.py in <module>()
      1 from .plot_linear_svc_regularization import plot_linear_svc_regularization
----> 2 from .plot_interactive_tree import plot_tree_progressive, plot_tree_partition
      3 from .plot_animal_tree import plot_animal_tree
      4 from .plot_rbf_svm_parameters import plot_svm
      5 from .plot_knn_regression import plot_knn_regression

/Users/me/programs/py3/lib/python3.5/site-packages/mglearn/plot_interactive_tree.py in <module>()
      6 from sklearn.externals.six import StringIO  # doctest: +SKIP
      7 from sklearn.tree import export_graphviz
----> 8 from scipy.misc import imread
      9 from scipy import ndimage
     10 from sklearn.datasets import make_moons

ImportError: cannot import name 'imread'
`

After a pip install pillow this time it worked.

Thanks for your patience!

**Comment by amueller** [comment]
yes, pillow should be a dependency, which I missed.
Not sure how to fix it, apart from documenting it in this repo.

**Comment by DrPeterVanNostrand** [comment]
For me, installing pillow did not fix this import error.
Changing the two imports mentioned above from:

`from scipy.misc import imread`
 
to

`from scipy.misc.pilutil import imread`

worked for me on Mac + miniconda with the following packages:

```
Python==3.6.0
mglearn==0.1.3
Pillow==4.0.0
scipy==0.18.1
```

**Comment by amueller** [comment]
See my reply here: https://github.com/amueller/mglearn/issues/2

I added pillow to the dependencies everywhere and to the second print of the book. If the import fails with pillow installed, that's a scipy bug.

**Pull request closed without merging**
